### ISSUE TITLE
PositionalEncoding

### ISSUE THREAD

**Issue by tomguluson92** [zankner/IMask#1]
Hi Zack, 
    Thank you for providing the mask mechanism of `ViT`. When I dig into your code, I found a different implementation of `PositionalEncoding` between you and the lucidrains's `ViT`. 
    So could you please introduce a little bit about your `PositionalEncoding` and the original paper of it? 
    Thank you very much!

Samuel

**Comment by zankner** [comment]
Hey,

I'm gonna be merging the masked prediction into the lucidrains's repo soon, so this issue will go away. But to answer your question, I believe that the difference is that the PositionalEncoding in theirs can be learned whereas the one I am using is the same as the original transformer positional encoding mechanism. I believe that both are used or at least experimented with in the ViT paper, however.

Best,
Zack

**Comment by zankner** [comment]
Hey @tomguluson92 ,

I'm gonna be merging the masked prediction into the lucidrains's repo soon, so this issue will go away. But to answer your question, I believe that the difference is that the PositionalEncoding in theirs can be learned whereas the one I am using is the same as the original transformer positional encoding mechanism. I believe that both are used or at least experimented with in the ViT paper, however.

Best,
Zack

**Comment by tomguluson92** [comment]
> Hey @tomguluson92 ,
> 
> I'm gonna be merging the masked prediction into the lucidrains's repo soon, so this issue will go away. But to answer your question, I believe that the difference is that the PositionalEncoding in theirs can be learned whereas the one I am using is the same as the original transformer positional encoding mechanism. I believe that both are used or at least experimented with in the ViT paper, however.
> 
> Best,
> Zack

Thank you~

**Comment by tomguluson92** [comment]
> Hey @tomguluson92 ,
> 
> I'm gonna be merging the masked prediction into the lucidrains's repo soon, so this issue will go away. But to answer your question, I believe that the difference is that the PositionalEncoding in theirs can be learned whereas the one I am using is the same as the original transformer positional encoding mechanism. I believe that both are used or at least experimented with in the ViT paper, however.
> 
> Best,
> Zack

Thank you very much~
